---
apiVersion: v1
kind: Template
labels:
  template: "${REPO_NAME}-template"
metadata:
  name: "${REPO_NAME}-frontend-static-bc"
  creationTimestamp:
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: s2i-caddy
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: docker-registry.default.svc:5000/bbe4c3-tools/caddy:v2
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/bbe4c3-tools/caddy:v2
      generation:
      importPolicy: {}
      name: v1-stable
      referencePolicy:
        type: Local
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: "${REPO_NAME}-frontend-static"
  spec:
    lookupPolicy:
      local: false
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewBuild
    creationTimestamp:
    labels:
      build: "${REPO_NAME}-frontend-static"
    name: "${REPO_NAME}-frontend-static"
  spec:
    completionDeadlineSeconds: 600
    successfulBuildsHistoryLimit: 3
    failedBuildsHistoryLimit: 3
    nodeSelector:
    output:
      to:
        kind: ImageStreamTag
        name: "${REPO_NAME}-frontend-static:latest"
    postCommit: {}
    resources:
      requests:
        cpu: 500m
        memory: 1Gi
      limits:
        cpu: 1200m
        memory: 2Gi
    runPolicy: SerialLatestOnly
    source:
      dockerfile: |-
        FROM docker-registry.default.svc:5000/bbe4c3-tools/caddy:v2
        COPY /tmp/src/dist /srv
        COPY /tmp/src/Caddyfile /etc/caddy/Caddyfile
      images:
      - as:
        from:
          kind: ImageStreamTag
          name: "${REPO_NAME}-frontend:latest"
          namespace: "${NAMESPACE}"
        paths:
        - destinationDir: tmp
          sourcePath: /opt/app-root/src
      type: Dockerfile
    strategy:
      dockerStrategy:
        from:
          kind: ImageStreamTag
          name: caddy:v2
      type: Docker
parameters:
- name: REPO_NAME
  description: Application repository name
  required: true
- name: NAMESPACE
  description: Target namespace reference (i.e. 'k8vopl-dev')
  required: true