name: Run Cypress Tests

env:
  TARGET_ENV: "dev"

on: 
  workflow_run: # Run after cypress branch is deployed
    workflows: [Build & Deploy Frontend-DEV]
    types:
      - completed
    branches:
      - cypress
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: dev
    strategy:
      fail-fast: false
      matrix:
        container: [0, 1, 2]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > testing/cypress.env.json
      - name: Get tests for this container
        id: get-tests
        run: echo "SPEC_FILES=$(node testing/split-tests.js ${{ matrix.container }} 3)" >> $GITHUB_ENV
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: testing
          browser: chrome
          spec: |
            ${{ env.SPEC_FILES }}