name: Run Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Specify Folder
        run: |
              cd ./testing
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          project: ./testing
          browser: chrome